---
title: "Estimation of S-R relationship parameters for Haddock"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

# Haddock
## Standard estimation of the stock recruitement parameters of Haddock

```{r had_standard_estimation, echo=F }
load("species_data.RData")
HAD_data <- sp_data[[3]]

ssb <- HAD_data$SSB
rec <- HAD_data$recruitment

LL <- function(par){
  a <- exp(par[1])
  b <- exp(par[2])
  c <- exp(par[3])
  
  R <- a*ssb / (b+ssb)
  
  ll = dlnorm(rec, meanlog = log(R)-(c^2)/2, sdlog = c, log = T)
  ll <- ll + dnorm(log(b), log(1e4), 0.2) # adding a prior on b parameter to imporve the estimation
  -sum(ll)
}

LL_opt <- nlminb(start = log(c(1e6, 4e4, 2)),  objective = LL)
LL_opt

a.had.sd <- exp(LL_opt$par[1])
b.had.sd <- exp(LL_opt$par[2])
data <- data.frame(paramter_a = a.had.sd, paramter_b = b.had.sd)

sr.had.sd <- function(x){a.had.sd*x / (b.had.sd+x)}
s <- seq(0, 10e5, by = 1000)
plot(ssb, rec, bty = "l",  xlim = c(0, 10e4), ylim = c(0, 2e6))
lines(s, sr.had.sd(s))

```

## Estimation of the stock recruitement parameters of HADDOCK using the steepness h (fixed)

```{r HAD_steepness_fixed, echo=F}
#####################################################################################################
# estimation the stock recruitement parameters of Haddock using the steepness h (fixed)
#####################################################################################################


# ============================== input data for Haddock (stock assessement 2016) 

## Age
age <- seq(from = 0,  to = 8)

## M
M <- c(0.99, 0.72, 0.6, 0.5, 0.43, 0.4, 0.37, 0.36, 0.34)

## Mat
Mat <- c(0, 0, 1, 1, 1, 1, 1, 1, 1)

## Weight
W2014 <- c(0.055, 0.148, 0.315, 0.572, 0.824, 1.251, 1.617, 1.922, 2.115) # Weight 2014
W2015 <- c(0.07, 0.16, 0.32, 0.62, 0.87, 1.15, 1.65, 1.82, 2) # Weight 2015
W2016 <- c(0.08, 0.17, 0.32, 0.63, 0.93, 1.17, 1.63, 1.79, 1.97) # Weight 2016
W.data <- data.frame(W2014, W2015, W2016)
W <- apply(W.data, 1, mean) # mean weight 2014, 2015, 2016 


data <- data.frame(M = M, Mat = Mat, W = W)
row.names(data) <- age

## ssb and rec data
load("species_data.RData")
HAD_data <- sp_data[[3]]

ssb <- HAD_data$SSB
rec <- HAD_data$recruitment

# value of steepness from Meyers et al. 1999
h <- 0.74 

# ============================== Likelihood function : Estimation of R0  ============================== 

## likelihood function
LL <- function(par) {
  
  # parameters to estimate
  R0 <- exp(par[1])
  c <- exp(par[2])
  
  # abundance by age class 
  N <- rep(NA, 8)
  N[1] <- R0
  for (i in 1:8) { 
    N[i+1] <- N[i]*exp(-M[i]) 
  }
  
  data$N <-N
  S <- apply(data, 1, function(x) x[2]*x[3]*x[4])
  S0 <- sum(S)
  
  R <- 0.8*R0*h*ssb / (0.2*S0*(1-h) + ssb*(h-0.2))
  
  ll = dlnorm(rec, meanlog = log(R)-(c^2)/2, sdlog = c, log = T)
  
  -sum(ll)
}

LL_opt <- nlminb(start = log(c(10000, 0.2)),  objective = LL)
LL_opt

R0_est <- exp(LL_opt$par[1])

## Calculation of SO from R0 
## N
N <- rep(NA, 8)
N[1] <- R0_est
for (i in 1:8) { N[i+1] <- N[i]*exp(-M[i]) }

## S0   
data$N <- N
S <- apply(data, 1, function(x) x[2]*x[3]*x[4])
S0_est <- sum(S)

# ============================== plotting SRR

a.had.fixed.h <- (S0_est/R0_est) * (1-h)/(4*h)
b.had.fixed.h <- (5*h-1) / (4*h*R0_est)

sr.had.fixed.h <- function(x){ x / (a.had.fixed.h + b.had.fixed.h*x) }

s <- seq(0, 10e5, by = 1000)
plot(ssb, rec, bty = "l",  xlim = c(0, 1e5), ylim = c(0, 3e6),
     xlab = "ssb", ylab = "rec", main = "HAD SRR using the steepness parameter (fixed h)")
lines(s, sr.had.fixed.h(s))
```

## estimation of the stock recruitement parameters of HADDOCK using a prior on the steepness

```{r steepness.had.prior, echo=F}
#####################################################################################################
# estimation of the stock recruitement parameters of Haddock using a prior on the steepness h (z)
#####################################################################################################


# ============================== input data for Haddock (stock assessement 2016) 

## Age
age <- seq(from = 0,  to = 8)

## M
M <- c(0.99, 0.72, 0.6, 0.5, 0.43, 0.4, 0.37, 0.36, 0.34)

## Mat
Mat <- c(0, 0, 1, 1, 1, 1, 1, 1, 1)

## Weight
W2014 <- c(0.055, 0.148, 0.315, 0.572, 0.824, 1.251, 1.617, 1.922, 2.115) # Weight Haddock by age 2014
W2015 <- c(0.07, 0.16, 0.32, 0.62, 0.87, 1.15, 1.65, 1.82, 2) # Weight Haddock by age 2015
W2016 <- c(0.08, 0.17, 0.32, 0.63, 0.93, 1.17, 1.63, 1.79, 1.97) # Weight Haddock by age 2016
W.data <- data.frame(W2014, W2015, W2016)
W <- apply(W.data, 1, mean) # mean weight 2014, 2015, 2016 

data <- data.frame(M = M, Mat = Mat, W = W)
row.names(data) <- age

## ssb and rec data
load("species_data.RData")
HAD_data <- sp_data[[3]]

ssb <- HAD_data$SSB
rec <- HAD_data$recruitment

# ============================== adding a prior for the steepness parameter (from Meyers et al. 1999)

zmed <- 0.74
z20 <- 0.64
z80 <- 0.82

## sum of square of the difference at z20 and z80
ssq <- function(alpha){
  beta <- (alpha - 1/3) / zmed - alpha + 2/3
  z20.pred <- qbeta(p = 0.2, shape1 = alpha, shape2 = beta)
  z80.pred <- qbeta(p = 0.8, shape1 = alpha, shape2 = beta)
  return((z20.pred-z20)^2 + (z80.pred-z80)^2)
}

fit <- optim(par = 2, fn = ssq, method = "Brent", lower = 1, upper = 50)

alpha.hat <- fit$par
beta.hat <- (alpha.hat - 1/3) / zmed - alpha.hat + 2/3

# curve(dbeta(x, shape1 = alpha.hat, shape2 = beta.hat), from = 0, to = 1, n = 1e3)
# abline(v = qbeta(c(0.2, 0.5, 0.8), shape1 = alpha.hat, shape2 = beta.hat))
# abline(v = c(z20, zmed, z80), lty = 2)

# ============================== Likelihood function : Estimation of R0 using a prior en h

## likelihood function
LL <- function(par) {
  
  # parameters to estimate
  R0 <- exp(par[1])
  sdev <- exp(par[2])
  h <- exp(par[3])
  
  N <- rep(NA, 8)
  N[1] <- R0
  for (i in 1:8) { 
    N[i+1] <- N[i]*exp(-M[i]) 
  }
  
  # S0 
  data$N <- N
  S <- apply(data, 1, function(x) x[2]*x[3]*x[4])
  S0 <- sum(S)
  
  R <- 0.8*R0*h*ssb / (0.2*S0*(1-h) + ssb*(h-0.2))
  
  ll = dlnorm(rec, meanlog = log(R)-(sdev^2)/2, sdlog = sdev, log = T)
  llp <- ll + dbeta(h, shape1 = alpha.hat, shape2 = beta.hat) # adding the prior
  
  -sum(llp)
}

LL_opt <- nlminb(start = log(c(10000, 0.1, 0.8)),  objective = LL)
LL_opt

R0.hat <- exp(LL_opt$par[1])
h <- exp(LL_opt$par[3])

## Calculation of SO from R0 
## N
N <- rep(NA, 8)
N[1] <- R0.hat
for (i in 1:8) { N[i+1] <- N[i]*exp(-M[i]) }

## S0   
data$N <- N
S <- apply(data, 1, function(x) x[2]*x[3]*x[4])
S0_hat <- sum(S)

# ============================== plotting SRR

a.had.prior.h <- (S0_hat/R0.hat) * (1-h)/(4*h)
b.had.prior.h <- (5*h-1) / (4*h*R0.hat)

sr.had.prior.h <- function(x){ x / (a.had.prior.h + b.had.prior.h*x) }

s <- seq(0, 10e5, by = 1000)
plot(ssb, rec, bty = "l",  xlim = c(0, 1e5), ylim = c(0, 3e6),
     xlab = "ssb", ylab = "rec", main = "HAD SRR using a prior on the steepness parameter h")
lines(s, sr.had.prior.h(s))

```

# All Stock-Recruitement Relationships

```{r all.plots.cod, echo=F}
plot(ssb, rec, bty = "l",  xlim = c(0, 1e5), ylim = c(0, 3e6),
     xlab = "ssb", ylab = "rec", main = "HAD SRR")
lines(s, sr.had.prior.h(s), lty = 1)
lines(s, sr.had.fixed.h(s), lty = 2)
lines(s, sr.had.sd (s), lty = 3)
legend("topright", legend = c("a prior on h", "fixed h", "Standard estimation"), lty=1:3)
```
