---
title: "Estimation of S-R relationship parameters for the Whiting, Haddock and Cod "
output: html_document
# output: 
#   slidy_presentation: 
# template: quarterly_report.html # output: ioslides_presentation
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
library(kableExtra)
```



```{r stock_data, echo = F}
# Download stock parameters data from ices database

library(icesSAG)  

# WHG_data <- getSAG(stock = "whg.27.7b-ce-k", year = 2017, data = "summary")
# COD_data <- getSAG(stock = "cod.27.7e-k", year = 2017, data = "summary")
# HAD_data <- getSAG(stock = "had.27.7b-k", year = 2017, data = "summary")

load("species_data.RData")
# WHG_data <- sp_data[[1]]
COD_data <- sp_data[[2]]
HAD_data <- sp_data[[3]]
```

<br>

## COD

```{r COD1, echo = F}
ssb <- COD_data$SSB
rec <- COD_data$recruitment
# plot(ssb, rec)
```

**lag = 1**

```{r COD2, echo = F}
lag <- 1 # lag should be > 0
rec_lag1 <- rec[-c((length(rec)-lag + 1):length(rec)) ]
ssb_lag1 <- ssb[-c(1:lag)]

plot(ssb, rec)
points(ssb_lag1, rec_lag1, pch = 20, col = "blue")
legend ("topright", legend = c("lag = 0", "lag = 1"), col=c("black", "blue"), pch=c(1, 20), cex=0.8)
```

### Cod Likelihood function
Likelihood function to fit a Beverton and Holt model.
```{r Likelihood_COD}
LL <- function(par){
  a <- exp(par[1])
  b <- exp(par[2])
  c <- exp(par[3])
  
  R <- a*ssb_lag1 / (b+ssb_lag1)
  
  ll = dlnorm(rec_lag1, meanlog = log(R)-(c^2)/2, sdlog = c, log = T)
  ll <- ll + dnorm(log(b), log(1e4), 0.2) # adding a prior on b parameter to imporve the estimation
  -sum(ll)
}

LL_opt_cod <- optim(par = log(c(15e3, 1e4, 2)),  fn = LL)
LL_opt_cod
```


```{r plot_LL_COD, echo=F} 
a <- exp(LL_opt_cod$par[1])
b <- exp(LL_opt_cod$par[2])
data <- data.frame(paramter_a = a, paramter_b = b)
sr1 <- function(x){a*x / (b+x)}
s <- seq(0, 10e5, by = 1000)
plot(ssb_lag1, rec_lag1, bty = "l",  xlim = c(0, 3e4), ylim = c(0, 3e4),
     xlab = "ssb", ylab = "rec")
lines(s, sr1(s))
# text(ssb, rec, labels=WHG_data$Year, cex = 0.7, pos = 2)

kable(x = data, format = "pandoc", digits = 2, align = "c",
      col.names = c("paramter a", "paramter b"), caption = "The estimated Parameters of the Beverton and Holt model for cod")

```

<br>

```{r steepness_cod, echo=F}

## Age
age <- seq(from = 1,  to = 7)

## M
M <- c(0.512, 0.39496 ,0.47621, 0.42494, 0.45796, 0.33431, 0.33431)

## Mat
Mat <- c(0, 0.39, 0.87, 0.93, 1, 1, 1)

## Weight

W <- c(0.647, 1.310, 3.683, 6.700, 10.573, 11.453, 12.928)

data <- data.frame(M = M, Mat = Mat, W = W)
row.names(data) <- age


# ============================== Likelihood function : Estimation of R0  ============================== 

## loading data
load("species_data.RData")
COD_data <- sp_data[[2]]

lag <- 1
ssb <- COD_data$SSB
rec <- COD_data$recruitment

ssb <- ssb[-c(1:lag)]
rec <- rec[-c((length(rec)-lag + 1):length(rec)) ]

h <- 0.84 # value from Meyers et al. 1999

## likelihood function
LL <- function(par) {
  
  R0 <- exp(par[1])
  c <- exp(par[2])
  
  M <- M # vector of natural mortality by age 
  N <- rep(NA, 7)
  N[1] <- R0
  for (i in 1:6) { 
    N[i+1] <- N[i]*exp(-M[i]) 
  }
  
  data$N <-N
  S <- apply(data, 1, function(x) x[2]*x[3]*x[4])
  S0 <- sum(S)
  
  R <- 0.8*R0*h*ssb / (0.2*S0*(1-h) + ssb*(h-0.2))
  
  ll = dlnorm(rec, meanlog = log(R)-(c^2)/2, sdlog = c, log = T)
  
  -sum(ll)
}

LL_opt <- nlminb(start = log(c(10000, 0.2)),  objective = LL)


R0_est <- exp(LL_opt$par[1])

## S-R parameters

# Calculation of SO from R0 
## N
N <- rep(NA, 7)
N[1] <- R0_est
for (i in 1:6) { N[i+1] <- N[i]*exp(-M[i]) }

## S0   
data$N <- N
S <- apply(data, 1, function(x) x[2]*x[3]*x[4])
S0_est <- sum(S)


# =================================================
a_cod <- exp(LL_opt_cod$par[1])
b_cod <- exp(LL_opt_cod$par[2])

sr1 <- function(x){a_cod*x / (b_cod+x)}

# ================================================

a <- (S0_est/R0_est) * (1-h)/(4*h)
b <- (5*h-1) / (4*h*R0_est)

sr2 <- function(x){ x / (a + b*x) }

s <- seq(0, 10e5, by = 100)
plot(ssb, rec, bty = "l",  xlim = c(0, 3e4), ylim = c(0, 3e4),
     xlab = "ssb", ylab = "rec", main = "Stock-Recruitement relationship")
lines(s, sr2(s))
lines(s, sr1(s), lty = 2)
legend("topright", legend = c("With steepness", "Standard estimation"), lty=1:2)

```

*** 
<br>

## Haddok

```{r HAD1, echo = F}
ssb <- HAD_data$SSB
rec <- HAD_data$recruitment
 plot(ssb, rec)
```

### Haddock Likelihood function
Likelihood function to fit a Beverton and Holt model.
```{r Likelihood_HAD}
LL <- function(par){
  a <- exp(par[1])
  b <- exp(par[2])
  c <- exp(par[3])
  
  R <- a*ssb / (b+ssb)
  
  ll = dlnorm(rec, meanlog = log(R)-(c^2)/2, sdlog = c, log = T)
  ll <- ll + dnorm(log(b), log(1e4), 0.2) # adding a prior on b parameter to imporve the estimation
  -sum(ll)
}

LL_opt <- nlminb(start = log(c(1e6, 4e4, 2)),  objective = LL)
LL_opt
```


```{r plot_LL_HAD, echo=F} 
a <- exp(LL_opt$par[1])
b <- exp(LL_opt$par[2])
data <- data.frame(paramter_a = a, paramter_b = b)

sr3 <- function(x){a*x / (b+x)}
s <- seq(0, 10e5, by = 1000)
plot(ssb, rec, bty = "l",  xlim = c(0, 10e4), ylim = c(0, 2e6))
lines(s, sr3(s))
# text(ssb, rec, labels=WHG_data$Year, cex = 0.7, pos = 2)

kable(x = data, format = "pandoc", digits = 2, align = "c",
      col.names = c("paramter a", "paramter b"), 
      caption = "The estimated Parameters of the Beverton and Holt model for haddock")

```

<br>

```{r steepness_haddock, echo = F}
#####################################################################################################
# estimation the stock recruitement parameters of Haddock using the steepness h
#####################################################################################################

## Age
age <- seq(from = 0,  to = 8)

## M
M <- c(0.99, 0.72, 0.6, 0.5, 0.43, 0.4, 0.37, 0.36, 0.34)

## Mat
Mat <- c(0, 0, 1, 1, 1, 1, 1, 1, 1)

## Weight

W <- c(0.08, 0.17, 0.32, 0.63, 0.93, 1.17, 1.63, 1.79, 1.97)

data <- data.frame(M = M, Mat = Mat, W = W)
row.names(data) <- age

# ==============================3 Likelihood function : Estimation of R0  ============================== 

## loading data
load("species_data.RData")
HAD_data <- sp_data[[3]]

ssb <- HAD_data$SSB
rec <- HAD_data$recruitment
h <- 0.74 # value from Meyers et al. 1999

## likelihood function
LL <- function(par) {
  
  R0 <- exp(par[1])
  c <- exp(par[2])
  
  M <- M # vector of natural mortality by age 
  N <- rep(NA, 8)
  N[1] <- R0
  for (i in 1:8) { 
    N[i+1] <- N[i]*exp(-M[i]) 
  }
  
  data$N <-N
  S <- apply(data, 1, function(x) x[2]*x[3]*x[4])
  S0 <- sum(S)
  
  R <- 0.8*R0*h*ssb / (0.2*S0*(1-h) + ssb*(h-0.2))
  
  ll = dlnorm(rec, meanlog = log(R)-(c^2)/2, sdlog = c, log = T)
  
  -sum(ll)
}

LL_opt_had <- nlminb(start = log(c(10000, 0.2)),  objective = LL)


R0_est <- exp(LL_opt_had$par[1])

## S-R parameters

# Calculation of SO from R0 
## N
N <- rep(NA, 8)
N[1] <- R0_est
for (i in 1:8) { N[i+1] <- N[i]*exp(-M[i]) }

## S0   
data$N <- N
S <- apply(data, 1, function(x) x[2]*x[3]*x[4])
S0_est <- sum(S)


a_had <- (S0_est/R0_est) * (1-h)/(4*h)
b_had <- (5*h-1) / (4*h*R0_est)

sr4 <- function(x){ x / (a_had + b_had*x) }

s <- seq(0, 10e5, by = 1000)
plot(ssb, rec, bty = "l",  xlim = c(0, 1e5), ylim = c(0, 3e6),
     xlab = "ssb", ylab = "rec", main = "Stock-Recruitement relationship")
lines(s, sr4(s))
lines(s, sr3(s), lty = 2)
legend("topright", legend = c("With steepness", "Standard estimation"), lty=1:2)
```
